services:
  frontend:
    build: ./frontend
    container_name: billowry-frontend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    networks:
      - appnet

networks:
  appnet:
    driver: bridge